image: node:8

cache:
  paths:
    - node_modules/

stages:
  - test
  - publish

before_script:
  - npm install

test:lint:
  stage: test
  script:
    - npm run lint

test:node:8:
  stage: test
  script:
    - npm test

test:node:10:
  stage: test
  image: node:10
  script:
    - npm test

test:node:12:
  stage: test
  image: node:12
  script:
    - npm test

# Publish tagged versions to npm
publish:
  stage: publish
  only:
    - tags
    - triggers
  script:
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish