image: node:8

cache:
  paths:
    - node_modules/

stages:
  - test

before_script:
  - npm install

test:lint:  
  script:
    - npm run lint

test:node:8:
  script:
    - npm test

test:node:10:
  script:
    - npm test